spring:
  config:
    activate:
      on-profile: dev
    # .env 파일을 속성 소스로 추가
    import: optional:file:.env[.properties]
  
  # PostgreSQL 데이터베이스 초기화
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
  devtools:
    restart:
      additional-exclude: "**/mapper/**/*MapperImpl.class"
      log-condition-evaluation-delta: true

  # Batch 설정
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  # PostgreSQL DB 접속 정보
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:otboo}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA 설정 (PostgreSQL용)
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none  # schema.sql로 테이블 생성하므로 none
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 100
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    username:
    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always

otboo:
  storage:
    type: ${STORAGE_TYPE:local}
    #    local:
    #      root-path: ${STORAGE_LOCAL_ROOT_PATH:.otboo/storage}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
  
  # JWT 설정
  jwt:
    secret: ${JWT_SECRET:otboo-jwt-secret-key-for-development-only-change-in-production}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}  # 1시간 (밀리초)
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}  # 7일 (밀리초)
    issuer: ${JWT_ISSUER:otboo}

  # 보안 설정
  security:
    cookie:
      secure: false  # 개발환경에서는 false
      same-site: Lax  # 개발환경에서는 Lax
  
  # CORS 설정
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080,http://127.0.0.1:3000,http://127.0.0.1:8080}

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.samsamotot.otboo: DEBUG

server:
  port: ${SERVER_PORT:8080}

