spring:
  application:
    name: Otboo
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB # 한 번에 최대 업로드 가능 용량

  data:
    redis:
      repositories:
        enabled: false  # 개발 단계 Redis Repository 비활성화

kma:
  base-url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
  service-key: ${KMA_DECODING_KEY}

kakao.api:
  base-url: https://dapi.kakao.com
  key: ${KAKAO_API_KEY}

# 비동기 실행 설정
async:
  executors:
    main:
      core-size: 4
      max-size: 8
      queue-capacity: 200
      keep-alive-seconds: 60
    weather:
      core-size: 5
      max-size: 10
      queue-capacity: 1000
      keep-alive-seconds: 60

