spring:
  config:
    activate:
      on-profile: prod
  
  # 운영환경에서는 SQL 초기화 비활성화 (이미 테이블이 존재)
  sql:
    init:
      mode: never
  
  # PostgreSQL DB 접속 정보
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA 설정 (PostgreSQL용)
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate  # 운영환경에서는 스키마 검증만
    properties:
      hibernate:
        show_sql: false
        default_batch_fetch_size: 100
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized

server:
  port: ${SERVER_PORT:80}